---
- name: "Testing ansible interaction with windows - basic auth method"
  hosts: all
  gather_facts: true
  tasks:
    - name: "Check windows machine access using win_ping"
      win_ping:
          
    - name: "Create a file - if not present, updates if present"
      win_file:
        path: C:\Scripts\hello.ps1
        content: Write-Host "Hello, World!"
        state: touch

    - name: "Run a powershell script"
      win_shell: C:\Scripts\hello.ps1
      register: hello_out

    - debug: var=hello_out.stdout
