---
- name: "Testing ansible interaction with windows - basic auth method"
  hosts: aws_windows
  gather_facts: true
  tasks:
    - name: "Check windows machine access using win_ping"
      win_ping:
      
    - name: "Download git-client"
      win_get_url:
        url: 'https://github.com/git-for-windows/git/releases/download/v2.33.0.windows.2/Git-2.33.0.2-64-bit.exe'
        dest: 'C:\Windows\Temp\Git-1.9.5-preview20150319.exe'

    - name: "Install git-client"
      win_package:
        path: C:\Windows\Temp\Git-1.9.5-preview20150319.exe
        arguments: /SILENT
        product_id: Git_is1
        state: present


