---
- name: "Testing ansible interaction with windows - Basic auth option"
  hosts: own_windows
  gather_facts: true
  tasks:
    - name: "Check windows machine access using win_ping"
      win_ping:

    - name: "Uninstall current git version"
      win_package:
        arguments: /SILENT
        product_id: Git_is1
        state: absent
      
    - name: "Download git-client"
      win_get_url:
        url: 'https://github.com/git-for-windows/git/releases/download/v2.36.0.windows.1/Git-2.36.0-64-bit.exe'
        dest: 'C:\Windows\Temp\Git-2.36.0-64-bit.exe'

    - name: "Install downloaded version"
      win_package:
        path: C:\Windows\Temp\Git-2.36.0-64-bit.exe
        arguments: /SILENT
        product_id: Git_is1
        state: present


