---
- name: "Testing ansible interaction with windows - basic auth method"
  hosts: aws_windows
  gather_facts: true
  tasks:
    - name: "Check windows machine access using win_ping"
      win_ping:

    - name: "Create directory structure"
      win_file:
        path: C:\Scripts
        state: directory

    - name: "Save te result of 'whoami' in whoami_out"
      win_command: whoami
      register: whoami_out

    - debug: var=whoami_out.stdout

    - name: "Create an empty"
      win_file:
        path: C:\Scripts\hello_v2.ps1
        state: touch

    - name: "Copy content inside an empty file"
      win_copy:
        dest: C:\Scripts\hello_v2.ps1
        content: |
          Write-Host "Hello, World!"
          Write-Host "Hello, Monica!"
        state: touch

    - name: "Run a powershell script"
      win_shell: C:\Scripts\hello.ps1
      register: hello_out

    - debug: var=hello_out.stdout

    - name: "Run a powershell script"
      win_shell: C:\Scripts\hello_v2.ps1
      register: hello_out

    - debug: var=hello_out.stdout
